---
galaxy_info:
  author: George Miroshnykov
  description: Installs Mercurial client
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
  - system
