- name: allow passwordless sudo for "admin" group
  sudo: true
  lineinfile: >
    dest=/etc/sudoers
    regexp='^%admin ALL\='
    line='%admin ALL=(ALL) NOPASSWD:ALL'
    validate='visudo -cf %s'

- name: create users
  sudo: true
  user: >
    name={{ item.name | mandatory }}
    groups={{ item.groups | join (', ') if 'groups' in item else '' }}
    append=true
    shell={{ item.shell | default('/bin/bash') }}
  with_items: users

- name: populate authorized_keys
  sudo: true
  authorized_key: >
    user={{ item.0.name }}
    key="{{ item.1 }}"
    manage_dir=true
  with_subelements:
    - users
    - keys
